### ISSUE TITLE
API spec 에 schema 추가.

### ISSUE THREAD

**Issue by namjoo-kim-gachon** [namjoo-kim-gachon/tut01#1]
### 문제점
API spec 에서 아래의 문장이 여러번 반복되어서 verbose 합니다.

```yaml
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string

```

### 해결안

schema 기능을 이용해서 간결하게 바꿔준다.
